import test from 'node:test';
import assert from 'node:assert/strict';
import {createRpcJobRepository,type ClaimedJob} from '../../../backend/supabase/functions/_shared/db/repositories/jobs.ts';
import {createRpcSafetyConsumerPorts,createSafetyConsumerRegistry,createSafetyWorkerInvocation,type SafetyReadiness} from '../../../backend/supabase/functions/_shared/jobs/safety-consumers.ts';
import type {WorkerScopedInvocationPort,WorkerScopedRequest,WorkerRuntimeOutcome} from '../../../backend/supabase/functions/_shared/db/worker-runtime-client.ts';
import type {JsonValue} from '../../../backend/supabase/functions/_shared/contracts/common.ts';
import {loadRuntimeConfig} from '../../../backend/supabase/functions/_shared/config/env.ts';
import {JobExecutionUnknown} from '../../../backend/supabase/functions/_shared/jobs/retry.ts';
const id=(n:number)=>`ef114100-0000-4000-8000-${String(n).padStart(12,'0')}`,token=id(1),parent=id(2),lease=id(4),jobId=id(3),signal=new AbortController().signal;
const values:Record<string,string>={SUPABASE_URL:'https://local.invalid',SUPABASE_ANON_KEY:'synthetic-anon',SUPABASE_SERVICE_ROLE_KEY:'synthetic-service',INTERNAL_WORKER_SECRET:'s'.repeat(32),UPSTREAM_TIMEOUT_MS:'1000',MAX_REQUEST_BYTES:'65536',ALLOWED_ORIGINS:'[]'};
const config=loadRuntimeConfig(k=>values[k]),readiness:SafetyReadiness={scopedClaim:true,sharedBudgetContract:true,durableJournalContract:true,cancellationGuardAndAcl:true,reportGuardAndAcl:true,reportTerminalScheduleContract:true,storageProviderApproved:true};
const saved=(r:WorkerScopedRequest,result:JsonValue,state:WorkerRuntimeOutcome['state']='completed'):WorkerRuntimeOutcome=>({requestId:r.requestId,result,state,closedAt:state==='external_pending'?null:'2026-10-09T00:00:00Z',replayed:false});
const wire={jobId,leaseToken:lease,leaseExpiresAt:'2099-01-01T00:00:00Z',attempt:1,failedAttempts:0,kind:'cancellation_safety',payload:{identityId:id(5),generation:2}};
function mockPort(run:(r:WorkerScopedRequest)=>Promise<WorkerRuntimeOutcome>){const requests:WorkerScopedRequest[]=[],confirmed:WorkerScopedRequest[]=[],unknown:string[]=[];const port:WorkerScopedInvocationPort={parentRequestId:parent,globalToken:token,run:async r=>{requests.push(structuredClone(r));return run(r);},get:async()=>assert.fail('unexpected GET'),confirm:async r=>{confirmed.push(r);},unknown:async key=>{unknown.push(key);}};return{port,requests,confirmed,unknown};}
function ports(p?:WorkerScopedInvocationPort,fetchImpl:typeof fetch=async()=>assert.fail('unexpected request')){return createRpcSafetyConsumerPorts(config,{readiness,budget:{globalToken:token,signal,elapsed:()=>0,reserve:async()=>true,hasItemCapacity:()=>true,reserveItem:async()=>true},journal:{prepare:async()=>assert.fail('legacy journal is bypassed by real atomic port'),confirmed:async()=>assert.fail('legacy confirmation'),unknown:async()=>assert.fail('legacy unknown')},atomicInvocation:p},fetchImpl);}
test('safety claim and complete/yield use atomic full inputs and no raw RPC',async()=>{
 const f=mockPort(async r=>saved(r,r.operation==='job_claim'?{job:wire}:{jobId,status:'queued'})),opts={workerRunToken:token,supportedClaim:true,signal,atomicInvocation:f.port};
 const repo=createRpcJobRepository({rpc:async()=>assert.fail('raw RPC forbidden')},opts);opts.workerRunToken=id(99);
 const job=await repo.claim({workerId:id(6),kinds:['cancellation_safety'],leaseDurationMs:180000});assert.equal(job?.jobId,jobId);
 assert.equal(await repo.settle({jobId,leaseToken:lease,status:'queued'}),'applied');
 assert.deepEqual(f.requests.map(r=>r.operation),['job_claim','job_settlement']);assert.deepEqual(f.requests[0].input,{workerId:id(6),leaseSeconds:180,supportedKinds:['cancellation_safety']});assert.deepEqual(f.requests[1].input,{jobId,jobLeaseToken:lease,status:'queued',availableAt:null});assert.equal(new Set(f.requests.map(r=>r.requestId)).size,2);assert.equal(f.unknown.length,0);
});
test('claim null uses the atomic port and creates no settlement',async()=>{
 const f=mockPort(async r=>saved(r,{job:null})),repo=createRpcJobRepository({rpc:async()=>assert.fail('raw RPC')},{workerRunToken:token,supportedClaim:true,signal,atomicInvocation:f.port});assert.equal(await repo.claim({workerId:id(6),kinds:['report_retention'],leaseDurationMs:180000}),null);assert.equal(f.requests.length,1);
});
test('false claim proof and late DB effect remain unknown without a second claim',async()=>{
 for(const mode of['false','late']){const f=mockPort(async r=>{if(mode==='late')throw new Error('invocation_expired');return saved(r,{job:{...wire,jobId:id(99),kind:'review_summary'}});});const repo=createRpcJobRepository({rpc:async()=>assert.fail('raw')},{workerRunToken:token,supportedClaim:true,signal,atomicInvocation:f.port});await assert.rejects(repo.claim({workerId:id(6),kinds:['cancellation_safety'],leaseDurationMs:180000}),JobExecutionUnknown);assert.equal(f.requests.length,1);assert.equal(f.unknown.length,1);}
});
test('a legacy no-op journal cannot enable production safety mutation',async()=>{
 const registry=createSafetyConsumerRegistry(ports().consumers);assert.deepEqual(registry,{});
 let calls=0;const repo=createRpcJobRepository({rpc:async()=>{calls++;return{job:null};}},{workerRunToken:token,supportedClaim:true,signal,claimJournal:{prepare:async()=>{},confirmed:async()=>{},unknown:async()=>{}}});await assert.rejects(repo.claim({workerId:id(6),kinds:['cancellation_safety'],leaseDurationMs:180000}),/SAFETY_ATOMIC_INVOCATION_REQUIRED/);assert.equal(calls,0);
});
const task={taskId:id(10),taskLeaseToken:id(11),taskExpiresAt:'2098-01-01T00:00:00Z',reportId:id(12),closureRevision:1,kind:'storage_object' as const,assetId:id(13),bucketId:'report-evidence' as const,objectName:`${id(12)}/${id(13)}.png`,objectId:id(14),retentionDueAt:'2026-01-01T00:00:00Z',closureProofId:id(15)};
const reportJob:ClaimedJob={jobId,leaseToken:lease,leaseUntil:'2099-01-01T00:00:00Z',failedAttempts:0,reference:{kind:'report_retention',reportId:task.reportId,closureProofId:task.closureProofId}};
test('claim restores only the exact original task after pathless stored102 result',async()=>{
 const{bucketId:_,objectName:__,...pathless}=task;const f=mockPort(async r=>saved(r,pathless));let queries=0;
 const p=ports(f.port,async(url,init)=>{assert.equal(new URL(String(url)).pathname,'/rest/v1/rpc/check_report_retention_task');const args=JSON.parse(String(init?.body));assert.deepEqual(args,{p_task_id:task.taskId,p_task_lease_token:task.taskLeaseToken,p_job_id:jobId,p_job_lease_token:lease,p_global_token:token,p_object_id:task.objectId});queries++;return Response.json(task);});
 assert.deepEqual(await p.consumers.reportClaim({requestId:id(20),jobId,jobLeaseToken:lease,globalToken:token},signal),task);assert.equal(queries,1);assert.equal(f.requests[0].requestId,id(20));assert.ok(!JSON.stringify(f.requests).includes(task.objectName));
 const mismatch=ports(f.port,async()=>Response.json({...task,taskLeaseToken:id(99)}));await assert.rejects(mismatch.consumers.reportClaim({requestId:id(21),jobId,jobLeaseToken:lease,globalToken:token},signal),/INVALID_RETENTION_TASK/);
});
test('metadata zero/null uses atomic proof without Storage or fabricated task',async()=>{
 const f=mockPort(async r=>saved(r,null)),p=ports(f.port);assert.equal(await p.consumers.reportClaim({requestId:id(22),jobId,jobLeaseToken:lease,globalToken:token},signal),null);assert.equal(f.requests[0].operation,'report_task_claim');
 const metadata={...task,kind:'report_metadata' as const,assetId:null,bucketId:null,objectName:null,objectId:null};const g=mockPort(async r=>saved(r,{taskId:metadata.taskId,status:'completed',alreadyApplied:false})),m=ports(g.port);const hash=await m.consumers.metadataEvidence(metadata,reportJob);await m.consumers.reportComplete({requestId:id(23),task:metadata,jobId,jobLeaseToken:lease,globalToken:token,evidenceSha256:hash},signal);assert.equal(g.requests[0].predecessorRequestId,undefined);assert.ok(g.requests[0].operation === "report_task_complete");assert.equal(g.requests[0].input.objectId,null);assert.equal(g.confirmed.length,0);
});
test('Storage preserves adapter checks, BEGIN->ACK->complete keys and deferred BEGIN confirmation',async()=>{
 let deleted=false,ackValue:JsonValue=null,deletes=0;const order:string[]=[];
 const f=mockPort(async r=>{order.push(r.operation);if(r.operation==='report_storage')return saved(r,{taskId:task.taskId,dispatchId:id(30),alreadyApplied:false},'external_pending');if(r.operation==='report_storage_ack'){ackValue={receiptId:id(31),taskId:task.taskId,assetId:task.assetId,objectId:task.objectId,ackSha256:r.input.ackSha256};return saved(r,ackValue);}return saved(r,{taskId:task.taskId,status:'completed',alreadyApplied:false});});
 f.port.confirm=async r=>{order.push('confirm:'+r.operation);f.confirmed.push(r);};
 const p=ports(f.port,async(url,init)=>{const path=new URL(String(url)).pathname;if(path==='/rest/v1/rpc/check_report_retention_task')return Response.json(task);if(path==='/rest/v1/rpc/get_report_retention_delete_ack')return Response.json(ackValue);if(path==='/storage/v1/object/report-evidence'&&init?.method==='DELETE'){deletes++;deleted=true;return Response.json([{id:task.objectId,name:task.objectName,bucket_id:task.bucketId}]);}if(path.startsWith('/storage/v1/object/info/authenticated/'))return deleted?new Response(null,{status:404}):Response.json({id:task.objectId,name:task.objectName,bucket_id:task.bucketId,content_type:'image/png',size:64});if(path.startsWith('/storage/v1/object/authenticated/'))return new Response(null,{status:404});assert.fail('unexpected adapter request');});
 const proof=await p.consumers.reportStorage(task,reportJob,signal,id(32));assert.equal(deletes,1);assert.deepEqual(order,['report_storage','report_storage_ack']);assert.equal(f.confirmed.length,0);
 await p.consumers.reportComplete({requestId:id(33),task,jobId,jobLeaseToken:lease,globalToken:token,evidenceSha256:proof.evidenceSha256},signal);
 assert.deepEqual(order,['report_storage','report_storage_ack','report_task_complete','confirm:report_storage']);assert.equal(f.requests[0].requestId,id(32));assert.equal(f.requests[1].predecessorRequestId,id(32));assert.equal(f.requests[2].predecessorRequestId,f.requests[1].requestId);assert.equal(f.requests[2].requestId,id(33));assert.equal(f.confirmed[0].requestId,id(32));assert.ok(!JSON.stringify(f.requests).includes(task.objectName));
});
test('lost/replayed BEGIN receipt and existing ACK without original child chain never send DELETE',async()=>{
 for(const existing of[false,true]){let deletes=0;const ack={receiptId:id(31),taskId:task.taskId,assetId:task.assetId,objectId:task.objectId,ackSha256:'a'.repeat(64)};const f=mockPort(async r=>({...saved(r,{taskId:task.taskId,dispatchId:id(30),alreadyApplied:false},'external_pending'),replayed:true}));const p=ports(f.port,async(url,init)=>{const path=new URL(String(url)).pathname;if(init?.method==='DELETE'){deletes++;assert.fail('DELETE forbidden');}if(path==='/rest/v1/rpc/check_report_retention_task')return Response.json(task);if(path==='/rest/v1/rpc/get_report_retention_delete_ack')return Response.json(existing?ack:null);if(path.startsWith('/storage/v1/object/info/authenticated/'))return existing?new Response(null,{status:404}):Response.json({id:task.objectId,name:task.objectName,bucket_id:task.bucketId,content_type:'image/png',size:64});if(path.startsWith('/storage/v1/object/authenticated/'))return new Response(null,{status:404});assert.fail('unexpected read');});await assert.rejects(p.consumers.reportStorage(task,reportJob,signal,id(32)));assert.equal(deletes,0);assert.equal(f.requests.filter(r=>r.operation==='report_storage_ack').length,0);}
});

test('whole cancellation invocation uses one bound port and needs no legacy no-op journals',async()=>{
 const f=mockPort(async r=>{switch(r.operation){case'due_enqueue':return saved(r,{enqueued:1});case'job_claim':return saved(r,{job:wire});case'cancellation_process':return saved(r,{status:'applied',generation:2,changed:true});case'job_settlement':return saved(r,{jobId,status:'succeeded'});default:assert.fail('unexpected operation');}});
 const reserved:string[]=[];let reads=0;
 const invoke=createSafetyWorkerInvocation(config,{readiness,atomicInvocation:f.port,allocate:()=>({maxJobsPerRun:1,enqueueLimit:1}),reserve:async()=>true,reserveItem:async(_token,item)=>{assert.equal(_token,token);reserved.push(item.jobId);return true;},elapsed:()=>0,workerId:id(6),jobLeaseDurationMs:180000,retry:{maxAttempts:3,baseDelayMs:1000,maxDelayMs:5000},now:()=>new Date('2026-10-09T00:00:00Z')},async(url)=>{assert.equal(new URL(String(url)).pathname,'/rest/v1/rpc/read_worker_run_budget');reads++;return Response.json({remainingMs:60000});});
 const result=await invoke(token,'cancellation_safety',{limit:1,remainingMs:60000,signal});assert.equal(result.status,'ran');if(result.status!=='ran')assert.fail('expected audited invocation');assert.equal(result.counts.claimed,1);assert.equal(result.counts.succeeded,1);assert.equal(result.counts.processedItems,1);assert.deepEqual(reserved,[jobId]);assert.deepEqual(f.requests.map(r=>r.operation),['due_enqueue','job_claim','cancellation_process','job_settlement']);assert.equal(new Set(f.requests.map(r=>r.requestId)).size,4);assert.equal(f.unknown.length,0);assert.equal(reads,4);
});
