import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const require=createRequire(new URL('../../../apps/mobile/package.json',import.meta.url));
const {chromium}=require('playwright');
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||(existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined);
const browser=await chromium.launch({headless:true,executablePath});
const page=await browser.newPage({viewport:{width:390,height:844}});
const failures=[],requests=[],checks=[];
page.on('pageerror',e=>failures.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(process.env.PREVIEW_URL||'http://127.0.0.1:8087'))requests.push(r.url());});
const output=process.env.SCREENSHOT_DIR||'/tmp/yumidang-mobile-check';await mkdir(output,{recursive:true});
const click=async name=>page.getByRole('button',{name,exact:true}).last().click();
const text=async()=>page.locator('body').innerText();
const preview=async()=>{await click('프로토타입 상태와 화면 목록');};
const screen=async(label,id)=>{await preview();await click(`${label} ${id} ›`);await page.waitForTimeout(120);};
const role=async name=>{await preview();await click(name);};
const check=(label,condition)=>{assert.ok(condition,label);checks.push(label);console.log('PASS',label);};
try{
 await page.goto(process.env.PREVIEW_URL||'http://127.0.0.1:8087');await page.waitForTimeout(500);
 await screen('공고 상세','S02');check('anonymous author name and exact meeting are absent from DOM',!(await text()).includes('박수빈')&&!(await text()).includes('종합안내 데스크 앞'));
 check('anonymous neutral login guard exists',(await text()).includes('동행인은 로그인 후 확인할 수 있어요'));
 await click('동행인은 로그인 후 확인할 수 있어요');await click('네이버로 로그인');await page.waitForTimeout(450);check('login returns to originating post',page.url().includes('/post?id=post-2'));
 check('logged-in unconfirmed author is masked',(await text()).includes('박*빈')&&!(await text()).includes('박수빈'));
 const screens=[['홈','S00'],['둘러보기','S01'],['공고 상세','S02'],['공고 작성','S03'],['등록 전 확인','S04'],['로그인','S05'],['가입 프로필','S06'],['카테고리','S09'],['행사 목록','S09-2'],['행사 상세','S09-3'],['채팅 목록','S10'],['대화방','S11'],['알림','S12'],['마이페이지','S13'],['동행인 프로필','S14'],['사진 편집','S15'],['성향 편집','S15-2'],['확정 약속','S16'],['후기 작성','S17'],['신청 철회·약속 취소','S18'],['안전 안내','S19'],['AI 동행 탐색','S20'],['계정 관리','S21']];
 for(const [label,id]of screens){await screen(label,id);check(`${id} renders without unmatched route`,!(await text()).includes('Unmatched Route'));await page.screenshot({path:`${output}/${id}.png`});}
 await preview();await click('다음 처리 실패: 꺼짐');await click('대화방 S11 ›');const input=page.getByRole('textbox',{name:'메시지를 입력해 주세요'}).last();await input.fill('함께 산책하고 싶어요.');await click('메시지 보내기');check('first message failure preserves input',(await input.inputValue())==='함께 산책하고 싶어요.');check('failure creates no application',(await text()).includes('첫 메시지를 보내기 전에는 신청이나 작성자 알림이 생성되지 않아요.'));
 await click('메시지 보내기');check('successful first send establishes application',(await text()).includes('대화 후 서로 결정해요')&&await input.inputValue()==='');
 await role('작성자');await click('대화방 S11 ›');await click('이 신청자에게 확정 요청');check('host request awaits final consent',(await text()).includes('상대의 최종 동의를 기다리고 있어요.'));
 await role('신청자');await click('대화방 S11 ›');await click('최종 동의 수락');check('final acceptance reveals full participant name',(await text()).includes('박수빈')&&(await text()).includes('우리 약속이 정해졌어요'));
 await click('일정·장소 변경 제안');const kstInput=ms=>new Date(ms+9*3600000).toISOString().slice(0,16);const nextStart=Date.now()+4*86400000;await page.getByRole('textbox',{name:'새 시작 (한국시간)'}).last().fill(kstInput(nextStart));await page.getByRole('textbox',{name:'새 종료 (한국시간)'}).last().fill(kstInput(nextStart+2*3600000));await click('서울숲');await click('변경 제안 보내기');await role('작성자');await click('대화방 S11 ›');await click('변경 수락');check('accepted location change updates exact address instead of retaining old address',(await text()).includes('서울 성동구 뚝섬로 273')&&!(await text()).includes('서울 영등포구 여의동로 330'));await role('신청자');
 await screen('후기 작성','S17');await click('☺ 좋아요');await click('5점');await page.getByRole('textbox',{name:'한마디 후기 (선택)'}).last().fill('대화가 편안하고 즐거웠어요.');await click('평가 제출하기');
 await preview();check('one submitted review remains private before deadline',(await text()).includes('현재 후기 1개 · 공개 0개'));
 await click('상대 후기 작성');await click('☺ 좋아요');await click('4점');await click('평가 제출하기');await preview();check('both submitted reviews publish after actual completion',(await text()).includes('현재 후기 2개 · 공개 2개'));
 await click('분쟁 시작');check('existing public reviews remain public in dispute',(await text()).includes('현재 후기 2개 · 공개 2개'));await click('운영 숨김 전환');check('operational hiding removes visible review',(await text()).includes('현재 후기 2개 · 공개 0개'));
 await click('분쟁 해소');await click('신청자');await click('AI 동행 탐색 S20 ›');await click('서울 전시 ↗');await page.waitForTimeout(600);check('fixed non-model condition does not spend quota',(await text()).includes('오늘 0/20회'));
 const ai=page.getByRole('textbox',{name:'예: 서울에서 주말 전시 같이 볼 분'}).last();await ai.fill('부산 전시');await click('AI 메시지 보내기');await page.waitForTimeout(600);check('model request example spends exactly one quota',(await text()).includes('오늘 1/20회'));check('unsupported region has no false Seoul recommendations',(await text()).includes('지금 조건에 맞는 예시 동행이 없어요.'));
 await screen('홈','S00');await screen('AI 동행 탐색','S20');check('AI messages clear on screen exit',!(await text()).includes('부산 전시'));
 await screen('계정 관리','S21');await click('로그아웃');await role('신청자');await click('AI 동행 탐색 S20 ›');check('daily quota survives logout/login in preview',(await text()).includes('오늘 1/20회'));
 await preview();await click('예시 상태와 기기 초안 초기화');await role('신청자');await click('후기 작성 S17 ›');await click('☺ 좋아요');await click('5점');await click('평가 제출하기');await preview();await click('+24시간');check('one-sided review is still private at 24 hours',(await text()).includes('현재 후기 1개 · 공개 0개'));await click('작성 마감으로 이동');check('one-sided review publishes at actual completion plus seven days',(await text()).includes('현재 후기 1개 · 공개 1개'));
 await click('예시 상태와 기기 초안 초기화');await role('신청자');await click('대화방 S11 ›');await page.getByRole('textbox',{name:'메시지를 입력해 주세요'}).last().fill('만료 동의 확인');await click('메시지 보내기');await role('작성자');await click('대화방 S11 ›');await click('이 신청자에게 확정 요청');await preview();await click('+6시간');await click('신청자');await click('대화방 S11 ›');check('final consent expires at six hours while application remains',(await text()).includes('신청 철회')&&!await page.getByRole('button',{name:'최종 동의 수락',exact:true}).count());
 await preview();await click('예상 종료 직후로 이동');await click('확정 약속 S16 ›');await click('본인 완료 확인');check('one completion check enables early review without finishing both sides',(await text()).includes('비공개 후기 선제출'));await preview();await click('+24시간');await click('확정 약속 S16 ›');check('automatic completion runs after expected end plus 24 hours',(await text()).includes('동행 완료'));
 await preview();await click('예시 상태와 기기 초안 초기화');await role('신청자');await click('공고 작성 S03 ›');await page.getByRole('textbox',{name:'공고 제목 *'}).last().fill('기기에 저장할 예시 초안');await click('작성 중인 내용 임시저장');await page.waitForTimeout(200);check('draft is persisted in device storage',await page.evaluate(()=>Object.keys(localStorage).some(k=>k.includes('draft')&&localStorage.getItem(k).includes('기기에 저장할 예시 초안'))));
 await screen('둘러보기','S01');const search=page.getByRole('textbox',{name:'공고 제목, 장소, 주소, 행사명 검색'}).last();for(let i=0;i<12;i++){await search.fill('검색'+i);await click('검색하기');}await page.waitForTimeout(200);check('recent search device storage caps at ten',await page.evaluate(()=>Object.keys(localStorage).some(k=>k.includes('searches')&&JSON.parse(localStorage.getItem(k)).length===10)));
 await screen('계정 관리','S21');await click('로그아웃');check('logout deletes drafts and recent searches',await page.evaluate(()=>!Object.keys(localStorage).some(k=>k.includes('yumidang')&&(k.includes('draft')||k.includes('searches')))));
 await screen('가입 프로필','S06');await click('가입 완료');check('signup blocks completion without a profile photo',(await text()).includes('프로필 사진을 선택해 주세요.'));const chosen=page.waitForEvent('filechooser');await click('프로필 사진 선택');await (await chosen).setFiles(fileURLToPath(new URL('../../../apps/mobile/assets/stitch/peer.jpg',import.meta.url)));await page.waitForTimeout(350);await click('가입 완료');check('valid photo signup shows completion popup',(await text()).includes('가입 프로필을 완성했어요'));await page.screenshot({path:`${output}/S06-complete.png`});await click('유미당 시작하기');check('signup popup confirmation returns home',new URL(page.url()).pathname==='/');await page.getByRole('button',{name:'유미당 시작하기',exact:true}).last().waitFor({state:'hidden'});check('signup popup closes after confirmation',!await page.getByRole('button',{name:'유미당 시작하기',exact:true}).count());
 await page.setViewportSize({width:1440,height:1000});await screen('홈','S00');await page.screenshot({path:`${output}/desktop-home.png`});check('desktop frame has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 check('no external API or model request made',requests.length===0);check('no runtime page errors',failures.length===0);
 console.log(JSON.stringify({checks:checks.length,screenShots:screens.length+2,errors:failures,externalRequests:requests}));
}catch(e){await page.screenshot({path:`${output}/failure.png`});console.error((await text()).slice(-3500));throw e;}finally{await browser.close();}
